FROM python:3.11-slim
WORKDIR /app
COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y libmagic1
COPY api ./api
COPY shared/ ./shared/
CMD ["uvicorn","api.main:app","--host","0.0.0.0","--port","8000"]